version: '3.4'

services:
  discord.client:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - READ_DB_SYNC=true
      - READ_DB_URL=postgresql://root:password@postgres.db:5432/wisdom-v3
      - BACKUP_DB_SYNC=true

  postgres.db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: wisdom-v3
    volumes:
      - type: volume
        source: postgres-volume-data
        target: /var/lib/postgresql/data

volumes:
  postgres-volume-data:
