export enum DomainEventNames {
  QUOTE_SUBMITTED = 'QUOTE_SUBMITTED',
  PENDING_QUOTE_ACCEPTED = 'PENDING_QUOTE_ACCEPTED',
  PENDING_QUOTE_CANCELLED = 'PENDING_QUOTE_CANCELLED',
  QUOTE_RECEIVED = 'QUOTE_RECEIVED',
  RECEIVE_INTERACTED = 'RECEIVE_INTERACTED',
}
