export enum DomainEventNames {
  QUOTE_SUBMITTED = 'QUOTE_SUBMITTED',
  PENDING_QUOTE_ACCEPTED = 'PENDING_QUOTE_ACCEPTED',
  PENDING_QUOTE_CANCELLED = 'PENDING_QUOTE_CANCELLED',
  PENDING_QUOTE_EXPIRATION_ACKNOWLEDGED = 'PENDING_QUOTE_EXPIRATION_ACKNOWLEDGED',
  QUOTE_RECEIVED = 'QUOTE_RECEIVED',
  RECEIVE_CREATED = 'RECEIVE_CREATED',
  RECEIVE_REACTED = 'RECEIVE_REACTED',
  QUOTE_MESSAGE_DETAILS_UPDATED = 'QUOTE_MESSAGE_DETAILS_UPDATED',
}
