export enum DomainErrorCodes {
  QUOTE_APPROVED,
  QUOTE_CANCELLED,
  QUOTE_EXPIRED,
  QUOTE_INVALID_EXPIRATION_ACK,
  REACTION_INVALID_KARMA,
  REACTION_DUPLICATE_USER,
  PENDING_QUOTE_USER_ALREADY_VOTED,
  PENDING_QUOTE_USER_NOT_VOTED,
}
