version: '3.4'

services:
  discord.client:
    depends_on:
      - postgres.db
    # points to the root of this repository
    build: ../../../.
    restart: unless-stopped
    env_file:
      - discord.env
    environment:
      - READ_DB_SYNC=true
      - READ_DB_URL=postgresql://root:password@postgres.db:5432/readmodel

      - STATS_DB_SYNC=true
      - STATS_DB_URL=postgresql://root:password@postgres.db:5432/statsmodel

      - BACKUP_DB_SYNC=true
      - LOGGING_LEVEL=debug

  postgres.db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - type: volume
        source: postgres-volume-data
        target: /var/lib/postgresql/data
      - ../../common/postgres-init:/docker-entrypoint-initdb.d

volumes:
  postgres-volume-data:
