version: '3.4'

services:
  mysql.db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backup
    volumes:
      - type: volume
        source: mysql-volume-data
        target: /var/lib/mysql

  postgres.db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - type: volume
        source: postgres-volume-data
        target: /var/lib/postgresql/data
      - ../common/postgres-init:/docker-entrypoint-initdb.d

volumes:
  mysql-volume-data:
  postgres-volume-data:
